<?php

namespace Macke;

//include __DIR__ . '/../pmrvic/osnove-php/Primjer_autoload/autoload.php';
//include '/pmrvic/osnove-php/Primjer_autoload/autoload.php';
//include ($_SERVER["DOCUMENT_ROOT"].'/pmrvic/osnove-php/Primjer_autoload/autoload.php');
include './../pmrvic/osnove-php/Primjer_autoload/class/Macke/Cat.class.php';


//include 'Cat.class.php';
use Macke\Cat;
//use PHPUnit\Framework\TestCase;



/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-19 at 00:22:20.
 */
class CatTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Cat
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    
      $this->object = new Cat();
  
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }

  /**
   * @covers Macke\Cat::says
   * @todo   Implement testSays().
   */
  public function testSays() {
    // Remove the following lines when you implement this test.
     $this->assertEquals($this->object->says(),"meoow");
  }

  /**
   * @covers Macke\Cat::prede
   * @todo   Implement testPrede().
   */
  public function testPrede() {
    // Remove the following lines when you implement this test.
$this->assertEquals($this->object->prede(),"Prrrrrr");
  }

}
